version: 2.1

jobs:
  checkout:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.0-browsers
    steps:
      - checkout
      - save_cache:
          key: v0-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/nest-ci-cd
  dependencies:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.0-browsers
    steps:
      - restore_cache:
          key: v0-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/nest-ci-cd/node_modules

workflows:
  version: 2
  ci:
    jobs:
      - checkout
      - dependencies:
          requires:
            - checkout
