version: 2.1

jobs:
  checkout:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.1
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - nest-ci-cd
  dependencies:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.1
    steps:
      - attach_workspace:
          at: ~/nest-ci-cd
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/nest-ci-cd/node_modules
  lint:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.0-browsers
    steps:
      - attach_workspace:
          at: ~/nest-ci-cd
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: ESLint
          command: npm run lint
      - run:
          name: Prettier
          command: npm run prettier:check
  test:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.0-browsers
    steps:
      - attach_workspace:
          at: ~/nest-ci-cd
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm run test
      - run:
          name: E2E
          command: npm run test:e2e
  build:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.0-browsers
    steps:
      - attach_workspace:
          at: ~/nest-ci-cd
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: v0-build-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/nest-ci-cd/dist/nest-build


workflows:
  version: 2
  ci:
    jobs:
      - checkout
      - dependencies:
          requires:
            - checkout
      - lint:
          requires:
            - dependencies
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
