version: 2.1

jobs:
  dependencies:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.1
    steps:
      - checkout
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/nest-ci-cd/node_modules
  lint:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.1
    steps:
      - checkout
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: ESLint
          command: npm run lint
      - run:
          name: Prettier
          command: npm run prettier:check
  test:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.1
    steps:
      - checkout
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm run test
  build:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.1
    steps:
      - checkout
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build

workflows:
  version: 2
  ci:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
