version: 2.1

jobs:
  dependencies:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.1
    steps:
      - checkout:
          path: ~/nest-ci-cd
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/nest-ci-cd/node_modules
  lint:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.0-browsers
    steps:
      - checkout:
          path: ~/nest-ci-cd
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: ESLint
          command: npm run lint
      - run:
          name: Prettier
          command: npm run prettier:check
  test:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.0-browsers
    steps:
      - checkout:
          path: ~/nest-ci-cd
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm run test
  build:
    working_directory: ~/nest-ci-cd
    docker:
      - image: cimg/node:18.9.0-browsers
    steps:
      - checkout:
          path: ~/nest-ci-cd
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  ci:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
